import { Router } from "express";
import employeeRoutes from "./employee.routes";
import departmentRoutes from "./department.routes";
import tenantRoutes from "./tenant.routes";
import userRoutes from "./user.routes";
import authRoutes from "./auth.routes";
import accountRoutes from "./account.routes";
import transactionRoutes from "./transaction.routes";
import inventoryRoutes from "./inventory.routes";
import purchaseOrderRoutes from "./purchaseOrder.routes";
import dashboardRoutes from "./dashboard.routes";
import auditLogRoutes from "./auditLog.routes";
import notificationRoutes from "./notification.routes";
import reportRoutes from "./report.routes";
import salaryStructureRoutes from "./salaryStructure.routes";
import payrollRoutes from "./payroll.routes";
import attendanceRoutes from "./attendance.routes";
import leaveRoutes from "./leave.routes";
import essRoutes from "./ess.routes";
import assetRoutes from "./asset.routes";
import supplierRoutes from "./supplier.routes";
import purchaseRequestRoutes from "./purchaseRequest.routes";
import procurementRoutes from "./procurement.routes";
import leadRoutes from "./lead.routes";
import opportunityRoutes from "./opportunity.routes";
import crmRoutes from "./crm.routes";
import salesOrderRoutes from "./salesOrder.routes";
import invoiceRoutes from "./invoice.routes";
import paymentRoutes from "./payment.routes";
import revenueRoutes from "./revenue.routes";
import executiveRoutes from "./executive.routes";
import approvalRoutes from "./approval.routes";
import documentRoutes from "./document.routes";
import grnRoutes from "./grn.routes";
import stockMovementRoutes from "./stockMovement.routes";
import projectRoutes from "./project.routes";
import taskRoutes from "./task.routes";
import milestoneRoutes from "./milestone.routes";
import resourceAllocationRoutes from "./resourceAllocation.routes";
import timeEntryRoutes from "./timeEntry.routes";

const router = Router();

router.use("/employees", employeeRoutes);
router.use("/departments", departmentRoutes);
router.use("/tenants", tenantRoutes);
router.use("/users", userRoutes);
router.use("/auth", authRoutes);
router.use("/accounts", accountRoutes);
router.use("/transactions", transactionRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/purchase-orders", purchaseOrderRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/audit-logs", auditLogRoutes);
router.use("/notifications", notificationRoutes);
router.use("/reports", reportRoutes);
router.use("/salary-structures", salaryStructureRoutes);
router.use("/payrolls", payrollRoutes);
router.use("/attendances", attendanceRoutes);
router.use("/leaves", leaveRoutes);
router.use("/me", essRoutes);
router.use("/assets",assetRoutes);
router.use("/suppliers",supplierRoutes);
router.use("/purchase-requests",purchaseRequestRoutes);
router.use("/procurement",procurementRoutes);
router.use("/leads",leadRoutes);
router.use("/opportunities",opportunityRoutes);
router.use("/crm",crmRoutes);
router.use("/sales-orders",salesOrderRoutes);
router.use("/invoices",invoiceRoutes);
router.use("/payments",paymentRoutes);
router.use("/revenue",revenueRoutes);
router.use("/executive",executiveRoutes);
router.use("/approvals",approvalRoutes);
router.use("/documents",documentRoutes);
router.use("/grns",grnRoutes);
router.use("/stock-movements",stockMovementRoutes);
router.use("/projects",projectRoutes);
router.use("/tasks",taskRoutes);
router.use("/milestones",milestoneRoutes);
router.use("/resource-allocations",resourceAllocationRoutes);
router.use("/time-entries",timeEntryRoutes);

export default router;